CREATE TABLE "faculty" (
  "faculty_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "faculty_name" varchar NOT NULL
);

CREATE TABLE "post" (
  "post_id" int PRIMARY KEY,
  "post_name" varchar NOT NULL
);

CREATE TABLE "unit" (
  "unit_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "unit_name" varchar NOT NULL,
  "type" int NOT NULL
);

CREATE TABLE "workplace" (
  "workplace_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workplace_name" varchar NOT NULL,
  "faculty_id" int
);

CREATE TABLE "granter" (
  "granter_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "name_of_institute" varchar NOT NULL,
  "email" varchar NOT NULL,
  "country" varchar NOT NULL
);

CREATE TABLE "settlement" (
  "settlement_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grant_id" int NOT NULL,
  "date_received" date NOT NULL,
  "amount_foreign" float NOT NULL,
  "amount_LKR" float NOT NULL
);

CREATE TABLE "grantee" (
  "grantee_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "workplace_id" int NOT NULL,
  "post_id" int NOT NULL,
  "email" varchar NOT NULL,
  "phone" varhar NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "grant" (
  "grant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grantee_id" int NOT NULL,
  "granter_id" int NOT NULL,
  "faculty_id" int NOT NULL
);

CREATE TABLE "university" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "university_name" varchar
);

CREATE TABLE "staff" (
  "NIC" varchar PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "post_id" int,
  "phone" varchar NOT NULL,
  "workplace_id" int,
  "university_id" int,
  "pf_no" int UNIQUE
);

CREATE TABLE "staff_grant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_id" varchar NOT NULL,
  "grant_id" int NOT NULL,
  "type" int NOT NULL,
  "salary" int,
  "duration" varchar,
  "other_benefits" varchar,
  "course_fee" int
);

CREATE TABLE "Inventory" (
  "item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "date_of_borrowed" DATE NOT NULL,
  "status" varchar,
  "grant_id" int NOT NULL,
  "date_of_returned" DATE
);

CREATE TABLE "publication" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "link" varchar,
  "grant_id" int NOT NULL,
  "details" varchar
);

CREATE TABLE "role" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar NOT NULL,
  "description" varchar
);

CREATE TABLE "permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action" varchar NOT NULL,
  "table_name" INT NOT NULL
);

CREATE TABLE "role_permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Role_id" INT NOT NULL,
  "Permission_id" INT NOT NULL
);

CREATE TABLE "System_user" (
  "user_id" int PRIMARY KEY,
  "Email" varchar UNIQUE NOT NULL,
  "Name" varchar NOT NULL,
  "post_id" int NOT NULL,
  "Phone" varchar NOT NULL,
  "role_id" int NOT NULL,
  "unit_id" int NOT NULL,
  "Password" varchar NOT NULL
);

ALTER TABLE "workplace" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("faculty_id");

ALTER TABLE "settlement" ADD FOREIGN KEY ("grant_id") REFERENCES "grant" ("grant_id");

ALTER TABLE "grantee" ADD FOREIGN KEY ("workplace_id") REFERENCES "workplace" ("workplace_id");

ALTER TABLE "grant" ADD FOREIGN KEY ("grantee_id") REFERENCES "grantee" ("grantee_id");

ALTER TABLE "grant" ADD FOREIGN KEY ("granter_id") REFERENCES "granter" ("granter_id");

ALTER TABLE "grant" ADD FOREIGN KEY ("faculty_id") REFERENCES "faculty" ("faculty_id");

ALTER TABLE "staff" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id");

ALTER TABLE "staff" ADD FOREIGN KEY ("workplace_id") REFERENCES "workplace" ("workplace_id");

ALTER TABLE "staff" ADD FOREIGN KEY ("university_id") REFERENCES "university" ("id");

ALTER TABLE "staff_grant" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("NIC");

ALTER TABLE "staff_grant" ADD FOREIGN KEY ("grant_id") REFERENCES "grant" ("grant_id");

ALTER TABLE "Inventory" ADD FOREIGN KEY ("grant_id") REFERENCES "grant" ("grant_id");

ALTER TABLE "publication" ADD FOREIGN KEY ("grant_id") REFERENCES "grant" ("grant_id");

ALTER TABLE "role_permission" ADD FOREIGN KEY ("Role_id") REFERENCES "role" ("role_id");

ALTER TABLE "role_permission" ADD FOREIGN KEY ("Permission_id") REFERENCES "permission" ("id");

ALTER TABLE "System_user" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_id");

ALTER TABLE "System_user" ADD FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");

ALTER TABLE "System_user" ADD FOREIGN KEY ("unit_id") REFERENCES "unit" ("unit_id");
